### ISSUE TITLE
Not allowed to manually enter path

### ISSUE THREAD

**Issue by Bazooka8416** [hubertdungen/Stellaris_flexScript#1]
### FLEX SCRIPT has failed to find the Stellaris path automatically! ###

...

Would you like to follow a semi-autonomous way starting by searching a specific drive for the {subject} path or do you want to insert it manually?

> semi / 1 - Will initiate a semi-autonomous search for the Stellaris folder.
  {semi_description}.
> manual / 2 - Will ask for you to insert the path manually.
> retry / 3 - Will retry the fully autonomous search.
  (only usefull if you have changed installation folder path)

(semi/manual/retry) Your answer:  manual

...

### ERROR WHILE TRYING TO CALL FOR HELP ###

...

You have entered characters, words or phrases other than those that this software is programmed to respond to.

**Comment by hubertdungen** [comment]
@Bazooka8416 I think I've found the problem. Basically I didn't detect this problem because on both my desktop and laptop flexScript detects the mod and stellaris paths, so it never went to that menu in the tests. I tested the semi and the manual in the menu that detects it. I'll try to sort it out today if possible, if not tomorrow.

**Comment by hubertdungen** [comment]
I'm closing this because today I will release version 2.1.1 that fixes this bug. Thanks for sharing the problem.

**Comment by hubertdungen** [comment]
.
